wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
env:
  desc: null
  value: CartPole-v0
episode_length:
  desc: null
  value: 200
eps:
  desc: null
  value: 1.1920928955078125e-07
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0005
max_episode_reward:
  desc: null
  value: 200
